FROM golang:1.12.9-alpine
ENV GO111MODULE on
ENV GOPROXY https://goproxy.cn
RUN go get github.com/beego/bee
ENV APPNAME=school-web
WORKDIR $GOPATH/src
RUN mkdir -p $APPNAME
WORKDIR $GOPATH/src/$APPNAME
ADD go.mod .
ADD go.sum .
RUN go mod download
